name: Update streak stats

on:
  schedule:
    - cron: "2 16 * * *"
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Run any time this file is modified
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          fetch-depth: 0

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=material-palenight&hide_border=true&background=FFFFFF00&ring=FB8C01&fire=FB8C01&currStreakNum=EA55B9&currStreakLabel=C792EA
          path: streak.svg
          token: ${{ secrets.GHSTATS_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
